apiVersion: v2
name: observability-operator
version: 0.1.0
appVersion: "1.0"
description: Observability Operator Helm chart
type: application
dependencies:
  - name: otel-collector
    version: 0.1.0
    repository: "file://../otel_collector"
  - name: kepler
    version: 0.6.1
    repository: "https://sustainable-computing-io.github.io/kepler-helm-chart"
  - name: prometheus-node-exporter
    version: 4.55.0
    repository: "https://prometheus-community.github.io/helm-charts"
    condition: nodeExporter.enabled
  - name: kube-state-metrics
    version: 7.3.0
    repository: "https://prometheus-community.github.io/helm-charts"
    condition: kubeStateMetrics.enabled
  - name: fluent-bit
    version: 0.57.6
    repository: "https://fluent.github.io/helm-charts"
    condition: fluentBit.enabled
  - name: network-metrics-exporter
    version: 0.1.0
    repository: "https://gitlab.com/api/v4/projects/44429468/packages/helm/stable"
    condition: networkMetrics.enabled
