apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-operator
  labels:
    app: {{ .Release.Name }}-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}-operator
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-operator
    spec:
      containers:
        - name: operator
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          args:
            - "--scrape-interval={{ .Values.scrapeInterval }}"
            - "--target-ip={{ .Values.targetIP }}"
            - "--target-port={{ .Values.targetPort }}"
          resources:
            limits:
              cpu: {{ .Values.resources.limits.cpu }}
              memory: {{ .Values.resources.limits.memory }}
            requests:
              cpu: {{ .Values.resources.requests.cpu }}
              memory: {{ .Values.resources.requests.memory }}"
