otelCollector:
  clusterName: athens_k8s_cluster
  deploymentName: otel-collector
  replicas: 1
  configMapName: otel-collector-config-map
  serviceName: otel-collector-service
  image:
    registry: otel
    name: opentelemetry-collector-contrib
    tag: latest
  scrapeInterval: 8s
  evaluationInterval: 5s
  exporters:
    otlp:
      host: 147.102.13.108
      port: 4317
      tls:
        insecure: true
  pipelines:
    metrics:
      receivers:
        - prometheus
      exporters:
        - otlp
      processors:
        - resource
        - batch
