# Uncomment and fill in only the blocks for included dependencies.

# prometheus-node-exporter:
prometheus-node-exporter:
  fullnameOverride: node-exporter

otelCollector:
  clusterName: "staging-edge-de-03"
