otelCollector:
  clusterName: "athens_k8s_cluster"
  scrapeInterval: 5s
  evaluationInterval: 5s
  deploymentName: otel-collector
  configMapName: otel-collector-config
  configChecksum: "855826e82f3b65dddf197c3fa258960dc31d3ae13eee0bfd00f3c25f4a4e8654"
  serviceName: otel-collector
  replicas: 1
  image:
    registry: otel
    name: opentelemetry-collector-contrib
    tag: "0.98.0"
  exporters:
    otlp:
      host: "147.102.13.108"
      port: 4318
      tls:
        insecure: true
