otelCollector:
  clusterName: "prod-edge-factory-05"
  scrapeInterval: 20s
  evaluationInterval: 5s
  deploymentName: otel-collector
  configMapName: otel-collector-config
  configChecksum: "ab69239dfc1a0e72f18f9c1edbb976b9bcbaa6cb2096601211e626eeddd0ccd6"
  serviceName: otel-collector
  replicas: 1
  image:
    registry: otel
    name: opentelemetry-collector-contrib
    tag: "0.98.0"
  exporters:
    otlp:
      host: "factory-collector.prod"
      port: 4318
      tls:
        insecure: true