apiVersion: v2
name: observability_operator
description: Observability Operator for k8s-audit-south-01
type: application
version: 0.1.0
dependencies:
  - name: otel-collector
    version: 0.1.0
    repository: "file://../otel_collector"
  - name: kube-state-metrics
    version: 7.4.0
    repository: "https://prometheus-community.github.io/helm-charts"
  - name: fluent-bit
    version: 0.57.6
    repository: "https://fluent.github.io/helm-charts"