otelCollector:
  clusterName: "staging-edge-de-03"
  scrapeInterval: 15s
  evaluationInterval: 5s
  deploymentName: otel-collector
  configMapName: otel-collector-config
  configChecksum: "cf4ee3d584bf685e6be495805df28c3dc054064acfdc71f7311036552fe0b710"
  serviceName: otel-collector
  replicas: 1
  image:
    registry: otel
    name: opentelemetry-collector-contrib
    tag: "0.98.0"
  exporters:
    otlp:
      host: "collector.infra.local"
      port: 4318
      tls:
        insecure: true
