otelCollector:
  clusterName: "staging-edge-de-03"
  scrapeInterval: 15s
  evaluationInterval: 15s
  deploymentName: otel-collector
  configMapName: otel-collector-config
  configChecksum: "c0d43674114e94bc2fda1f097d0697abbbd369955a16cba90967224af52c3260"
  serviceName: otel-collector
  replicas: 1
  image:
    registry: otel
    name: opentelemetry-collector-contrib
    tag: "0.98.0"
  exporters:
    otlp:
      host: "collector.infra.local"
      port: 4318
      tls:
        insecure: true
