otelCollector:
  clusterName: "edge-campus-pt-01"
  scrapeInterval: 20s
  evaluationInterval: 5s
  deploymentName: otel-collector
  configMapName: otel-collector-config
  configChecksum: "02e612d31eff1479b75c5c1ceca5d9269d580e2dd50a4b9cfae5e2f76e935312"
  serviceName: otel-collector
  replicas: 1
  image:
    registry: otel
    name: opentelemetry-collector-contrib
    tag: "0.98.0"
  exporters:
    otlp:
      host: "otel-collector.monitoring.svc.cluster.local"
      port: 4318
      tls:
        insecure: true
