otelCollector:
  clusterName: "edge-campus-pt-01"
  scrapeInterval: 20s
  evaluationInterval: 5s
  deploymentName: otel-collector
  configMapName: otel-collector-config
  configChecksum: "632a6635c60ccd6f2646e63fedb7cccd982eea5c418f532c90b12ea974efa902"
  serviceName: otel-collector
  replicas: 1
  image:
    registry: otel
    name: opentelemetry-collector-contrib
    tag: "0.98.0"
  exporters:
    otlp:
      host: "otel-collector.monitoring.svc.cluster.local"
      port: 4318
      tls:
        insecure: true
