apiVersion: apps/v1
kind: Deployment
metadata:
  name: kepler
  labels:
    app: kepler
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kepler
  template:
    metadata:
      labels:
        app: kepler
    spec:
      containers:
        - name: kepler
          image: "kepler/kepler:0.6.1"
          args: []