otelCollector:
  clusterName: "prod-edge-factory-05"
  scrapeInterval: 20s
  evaluationInterval: 5s
  deploymentName: otel-collector
  configMapName: otel-collector-config
  configChecksum: "f4624ed9814efb6005469616689bf742b32da2fd27e80510b3f4254c977b45cc"
  serviceName: otel-collector
  replicas: 1
  image:
    registry: otel
    name: opentelemetry-collector-contrib
    tag: "0.98.0"
  exporters:
    otlp:
      host: "factory-collector.prod"
      port: 4318
      tls:
        insecure: true
