otelCollector:
  clusterName: "prod-edge-factory-05"
  scrapeInterval: 20s
  evaluationInterval: 20s
  deploymentName: otel-collector
  configMapName: otel-collector-config
  configChecksum: "192d955f7c4cfee9dd9748041063c640b40742ac4bd36497aa1d9909b366dd09"
  serviceName: otel-collector
  replicas: 1
  image:
    registry: otel
    name: opentelemetry-collector-contrib
    tag: "0.98.0"
  exporters:
    otlp:
      host: "factory-collector.prod"
      port: 4318
      tls:
        insecure: true