otelCollector:
  clusterName: "prod-edge-factory-05"
  scrapeInterval: 20s
  evaluationInterval: 5s
  deploymentName: otel-collector
  configMapName: otel-collector-config
  configChecksum: "f682db44964e69832910dbbcb54fda5e001145de5a14a1894293e2310f18d8f6"
  serviceName: otel-collector
  replicas: 1
  image:
    registry: otel
    name: opentelemetry-collector-contrib
    tag: "0.98.0"
  exporters:
    otlp:
      host: "factory-collector.prod"
      port: 4318
      tls:
        insecure: true
