apiVersion: v2
name: observability-operator
description: A Helm chart for deploying all components of the Observability Operator (OpenTelemetry Collector, Node Exporter, Kepler Exporter etc).
type: application
version: 0.1.0
appVersion: dev
dependencies:
  - name: kube-state-metrics
    version: 7.3.0
    repository: "https://prometheus-community.github.io/helm-charts"
  - name: prometheus-node-exporter
    version: 4.55.0
    repository: "https://prometheus-community.github.io/helm-charts"
  - name: kepler
    version: 0.6.1
    repository: "https://sustainable-computing-io.github.io/kepler-helm-chart"
  - name: network_latency
    alias: network-metrics-exporter
    version: 0.1.0
    repository: "https://gitlab.com/api/v4/projects/44429468/packages/helm/stable"
  - name: otel-collector
    version: 0.1.0
    repository: "file://../otel_collector"