otelCollector:
  clusterName: demo-cluster

  deploymentName: otel-collector
  replicas: 1

  configMapName: otel-collector-config-map
  serviceName: otel-collector-service

  image:
    registry: otel
    name: opentelemetry-collector-contrib
    tag: latest

  scrapeInterval: 5s
  evaluationInterval: 5s

  exporters:
    otlp:
      ip: 127.0.0.1
      port: 4318
    tls:
      insecure: true

  pipelines:
    traces:
      receivers: [otlp]
      exporters: [otlp]
      processors: [resource, batch]
    metrics:
      receivers: [otlp, prometheus]
      exporters: [otlp]
      processors: [resource, batch]
    logs:
      receivers: [otlp, k8s_events]
      exporters: [otlp]
      processors: [resource, batch]

  ports:
    otlp-grpc:
      port: 4317
      targetPort: 4317
    otlp-http:
      port: 4318
      targetPort: 4318