otelCollector:
  clusterName: demo-cluster

  deploymentName: otel-collector
  replicas: 1

  configMapName: otel-collector-config-map
  serviceName: otel-collector-service

  image:
    registry: otel
    name: opentelemetry-collector
    tag: latest

  scrapeInterval: 5s
  evaluationInterval: 5s

  exporters:
    otlp:
      host: observability-backend.default.svc.cluster.local
      port: 4318

    tls:
      insecure: true