otelCollector:
  clusterName: "staging-edge-de-03"
  scrapeInterval: 15s
  evaluationInterval: 5s
  deploymentName: otel-collector
  configMapName: otel-collector-config
  configChecksum: "19a5433bee472ff8983210cc2dbdcf9c146d4b1c47a258b5c9728f3ea8c9df8c"
  serviceName: otel-collector
  replicas: 1
  image:
    registry: otel
    name: opentelemetry-collector-contrib
    tag: "0.98.0"
  exporters:
    otlp:
      host: "collector.infra.local"
      port: 4318
      tls:
        insecure: true
