otelCollector:
  clusterName: "staging-edge-de-03"
  scrapeInterval: 15s
  evaluationInterval: 5s
  deploymentName: otel-collector
  configMapName: otel-collector-config
  configChecksum: "be31bda74a6b5c772f9a6981d5584a288a2b1c58e9897bd71fda73da344e0a69"
  serviceName: otel-collector
  replicas: 1
  image:
    registry: otel
    name: opentelemetry-collector-contrib
    tag: "0.98.0"
  exporters:
    otlp:
      host: "collector.infra.local"
      port: 4318
      tls:
        insecure: true
