otelCollector:
  clusterName: "datacenter-south-02"
  scrapeInterval: 10s
  evaluationInterval: 10s
  deploymentName: otel-collector
  configMapName: otel-collector-config
  configChecksum: "c31c475d1304528c64467e522c6f8425b0608beeb02c89f5e26f7b2288e0ec40"
  serviceName: otel-collector
  replicas: 1
  image:
    registry: otel
    name: opentelemetry-collector-contrib
    tag: "0.98.0"
  exporters:
    otlp:
      host: "otel-collector.observability.svc"
      port: 4318
      tls:
        insecure: true