otelCollector:
  clusterName: "datacenter-south-02"
  scrapeInterval: 10s
  evaluationInterval: 5s
  deploymentName: otel-collector
  configMapName: otel-collector-config
  configChecksum: "a949111df82abe23de5b8ff8e6120c271f9b198977c64a243836d265603d3157"
  serviceName: otel-collector
  replicas: 1
  image:
    registry: otel
    name: opentelemetry-collector-contrib
    tag: "0.98.0"
  exporters:
    otlp:
      host: "otel-collector.observability.svc"
      port: 4318
      tls:
        insecure: true
