otelCollector:
  clusterName: "app-telemetry-west-01"
  scrapeInterval: 10s
  evaluationInterval: 10s
  deploymentName: otel-collector
  configMapName: otel-collector-config
  configChecksum: "90fc53d765ec1dbb25523757f49cd5aeefb7ab3c9549e1f07eb7ea3ad21048ca"
  serviceName: otel-collector
  replicas: 1
  image:
    registry: otel
    name: opentelemetry-collector-contrib
    tag: "0.98.0"
  exporters:
    otlp:
      host: "telemetry-gateway.prod.svc"
      port: 4318
      tls:
        insecure: true
