otelCollector:
  clusterName: "app-telemetry-west-01"
  scrapeInterval: 10s
  evaluationInterval: 5s
  deploymentName: otel-collector
  configMapName: otel-collector-config
  configChecksum: "f9727a52e78c4a3636f072cfce67a3db0f3fa30f55c36db01bdc499f54264d6c"
  serviceName: otel-collector
  replicas: 1
  image:
    registry: otel
    name: opentelemetry-collector-contrib
    tag: "0.98.0"
  exporters:
    otlp:
      host: "telemetry-gateway.prod.svc"
      port: 4318
      tls:
        insecure: true
