otelCollector:
  clusterName: "cloud-prod-eu-1"
  scrapeInterval: 30s
  evaluationInterval: 5s
  deploymentName: otel-collector
  configMapName: otel-collector-config
  configChecksum: "aec7c91c201298b1374b79982d7df4e3a97f86018849c6ba9730166955dcdc3e"
  serviceName: otel-collector
  replicas: 1
  image:
    registry: otel
    name: opentelemetry-collector-contrib
    tag: "0.98.0"
  exporters:
    otlp:
      host: "otel-gateway.monitoring.svc.cluster.local"
      port: 4318
      tls:
        insecure: true
