otelCollector:
  clusterName: "lorca-cluster-2"
  scrapeInterval: 5s
  evaluationInterval: 5s
  deploymentName: otel-collector
  configMapName: otel-collector-config
  configChecksum: "e7e9b1713420418944ea65c604b29078052d75e56e3cd03424d0baf2b1b51203"
  serviceName: otel-collector
  replicas: 1
  image:
    registry: otel
    name: opentelemetry-collector-contrib
    tag: "0.98.0"
  exporters:
    otlp:
      host: "147.102.13.108"
      port: 4318
      tls:
        insecure: true