otelCollector:
  clusterName: "lorca-cluster-2"
  scrapeInterval: 15s
  evaluationInterval: 5s
  deploymentName: otel-collector
  configMapName: otel-collector-config
  configChecksum: "b9717e2ec650367ce98726c57bffcaf4113acadb5928e397326181857e1f0e4c"
  serviceName: otel-collector
  replicas: 1
  image:
    registry: otel
    name: opentelemetry-collector-contrib
    tag: "0.98.0"
  exporters:
    otlp:
      host: "147.102.13.108"
      port: 4318
      tls:
        insecure: true
