otelCollector:
  clusterName: athens-k8s-cluster
  deploymentName: otel-collector
  replicas: 1
  configMapName: otel-collector-config-map
  serviceName: otel-collector-service
  image:
    registry: otel
    name: opentelemetry-collector
    tag: latest
  scrapeInterval: 5s
  evaluationInterval: 5s
  exporters:
    otlp:
      host: 147.102.13.110
      port: 4318
  tls:
    insecure: true
  # Enable required scrape jobs based on requested signals
  scrapeConfigs:
    - job_name: "kepler"
      static_configs:
        - targets: ["127.0.0.1:9100"]
    - job_name: "node-exporter"
      static_configs:
        - targets: ["127.0.0.1:9100"]
    - job_name: "network-latency-agent"
      static_configs:
        - targets: ["147.102.13.200:9090", "127.0.0.1:9090"]
