otelCollector:
  clusterName: "edge-gw-probe-01"
  scrapeInterval: 15s
  evaluationInterval: 5s
  deploymentName: otel-collector
  configMapName: otel-collector-config
  configChecksum: "f4b278da09f575f19cb7976883de495d6717f9aa086bbfd1fb9823b6fbed3def"
  serviceName: otel-collector
  replicas: 1
  image:
    registry: otel
    name: opentelemetry-collector-contrib
    tag: "0.98.0"
  exporters:
    otlp:
      host: "probe-collector.edge.svc"
      port: 4318
      tls:
        insecure: true
