otelCollector:
  clusterName: "deep-obs-cluster-07"
  scrapeInterval: 5s
  evaluationInterval: 5s
  deploymentName: otel-collector
  configMapName: otel-collector-config
  configChecksum: "b3700a8f66d760bb56a98dfb1359352bafa0f6b79692bbf2ee08dc8b9206890d"
  serviceName: otel-collector
  replicas: 1
  image:
    registry: otel
    name: opentelemetry-collector-contrib
    tag: "0.98.0"
  exporters:
    otlp:
      host: "full-collector.ops.svc"
      port: 4318
      tls:
        insecure: true
