otelCollector:
  clusterName: "trace-only-staging-01"
  scrapeInterval: 30s
  evaluationInterval: 5s
  deploymentName: otel-collector
  configMapName: otel-collector-config
  configChecksum: "b804caf8cba9122781482633615504edf27e6e6599b2a40a2d6b10da856eb920"
  serviceName: otel-collector
  replicas: 1
  image:
    registry: otel
    name: opentelemetry-collector-contrib
    tag: "0.98.0"
  exporters:
    otlp:
      host: "trace-collector.staging.svc"
      port: 4318
      tls:
        insecure: true