otelCollector:
  clusterName: "trace-only-staging-01"
  scrapeInterval: 30s
  evaluationInterval: 5s
  deploymentName: otel-collector
  configMapName: otel-collector-config
  configChecksum: "4945b8997bf19a84a6480a3e6717e18b744f0d8d2f50aae81b8ff29ba53fb794"
  serviceName: otel-collector
  replicas: 1
  image:
    registry: otel
    name: opentelemetry-collector-contrib
    tag: "0.98.0"
  exporters:
    otlp:
      host: "trace-collector.staging.svc"
      port: 4318
      tls:
        insecure: true
