apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.otelCollector.configMapName }}
  labels:
    app: {{ .Values.otelCollector.deploymentName }}
data:
  collector.yaml: |
    extensions:
      health_check:
        endpoint: 0.0.0.0:13133
    receivers:
      prometheus:
        config:
          global:
            scrape_interval: {{ .Values.otelCollector.scrapeInterval }}
            evaluation_interval: {{ .Values.otelCollector.evaluationInterval }}
          scrape_configs:
            - job_name: "network-latency-agent"
              static_configs:
                - targets: ["147.102.13.200:9090"]
    processors:
      batch: {}
      resource:
        attributes:
          - key: cluster
            value: {{ .Values.otelCollector.clusterName }}
            action: insert
    exporters:
      otlp:
        endpoint: {{ .Values.otelCollector.exporters.otlp.host }}:{{ .Values.otelCollector.exporters.otlp.port }}
        tls:
          insecure: {{ .Values.otelCollector.exporters.tls.insecure }}
    service:
      pipelines:
        metrics:
          receivers: [prometheus]
          processors: [resource,batch]
          exporters: [otlp]
