apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.otelCollector.configMapName }}
data:
  otel-collector-config.yaml: |
    receivers:
      otlp:
        protocols:
          grpc: {}
          http: {}
    processors:
      batch: {}
      resource:
        attributes:
          - key: cluster
            value: "{{ .Values.otelCollector.clusterName }}"
            action: insert
    exporters:
      otlp:
        endpoint: "{{ .Values.otelCollector.exporters.otlp.host }}:{{ .Values.otelCollector.exporters.otlp.port }}"
        tls:
          insecure: {{ .Values.otelCollector.tls.insecure }}
    service:
      pipelines:
        metrics:
          receivers: [otlp]
          processors: [batch,resource]
          exporters: [otlp]
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.otelCollector.deploymentName }}
spec:
  replicas: {{ .Values.otelCollector.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.otelCollector.deploymentName }}
  template:
    metadata:
      labels:
        app: {{ .Values.otelCollector.deploymentName }}
    spec:
      serviceAccountName: otel-collector-serviceaccount
      containers:
        - name: otel-collector
          image: "{{ .Values.otelCollector.image.registry }}/{{ .Values.otelCollector.image.name }}:{{ .Values.otelCollector.image.tag }}"
          args: ["--config", "/conf/otel-collector-config.yaml"]
          volumeMounts:
            - name: config
              mountPath: /conf
      volumes:
        - name: config
          configMap:
            name: {{ .Values.otelCollector.configMapName }}