apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.otelCollector.deploymentName }}-serviceaccount
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.otelCollector.configMapName }}
data:
  otel-collector-config.yaml: |
    extensions:
      health_check:
        endpoint: "0.0.0.0:13133"
    receivers:
      prometheus:
        config:
          global:
            scrape_interval: {{ .Values.otelCollector.scrapeInterval }}
            evaluation_interval: {{ .Values.otelCollector.evaluationInterval }}
          scrape_configs:
            - job_name: "kepler"
              kubernetes_sd_configs:
                - role: "pod"
              relabel_configs:
                - source_labels: [__meta_kubernetes_pod_label_app_kubernetes_io_name]
                  regex: "kepler"
                  action: "keep"
                - source_labels: [__meta_kubernetes_pod_node_name]
                  target_label: node
            - job_name: "node-exporter"
              kubernetes_sd_configs:
                - role: "pod"
              relabel_configs:
                - source_labels: [__meta_kubernetes_pod_label_app_kubernetes_io_name]
                  regex: "prometheus-node-exporter"
                  action: "keep"
                - source_labels: [__meta_kubernetes_pod_node_name]
                  target_label: node
    processors:
      resource:
        attributes:
          - key: cluster
            value: "{{ .Values.otelCollector.clusterName }}"
            action: insert
      batch: {}
    exporters:
      otlp:
        endpoint: "{{ .Values.otelCollector.exporters.otlp.host }}:{{ .Values.otelCollector.exporters.otlp.port }}"
        tls:
          insecure: {{ .Values.otelCollector.exporters.tls.insecure }}
    service:
      pipelines:
        metrics:
          receivers: [prometheus]
          processors: [resource, batch]
          exporters: [otlp]
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.otelCollector.deploymentName }}
spec:
  replicas: {{ .Values.otelCollector.replicas }}
  selector:
    matchLabels:
      component: {{ .Values.otelCollector.deploymentName }}
  template:
    metadata:
      labels:
        component: {{ .Values.otelCollector.deploymentName }}
    spec:
      serviceAccountName: {{ .Values.otelCollector.deploymentName }}-serviceaccount
      containers:
        - name: otel-collector
          image: "{{ .Values.otelCollector.image.registry }}/{{ .Values.otelCollector.image.name }}:{{ .Values.otelCollector.image.tag }}"
          command:
            - "/otelcol"
            - "--config=/conf/otel-collector-config.yaml"
          volumeMounts:
            - name: config
              mountPath: /conf
      volumes:
        - name: config
          configMap:
            name: {{ .Values.otelCollector.configMapName }}
            items:
              - key: otel-collector-config.yaml
                path: otel-collector-config.yaml