apiVersion: v2
name: observability_operator
description: Observability Operator for lorca-cluster-2
type: application
version: 0.1.0
dependencies:
  - name: otel-collector
    version: 0.1.0
    repository: "file://../otel_collector"
