otelCollector:
  clusterName: "lorca-cluster-2"

kepler:
  fullnameOverride: kepler

network-latency:
  name: network-latency-agent
  target_hosts:
    - cluster: "lorca-cluster-2"
      host_ip:
        - "147.102.13.108"
        - "147.102.13.108"
        - "147102.13.108"
        - "147.102.13.109"
  parameters:
    interval: 15
