kepler:
  fullnameOverride: kepler

network-latency:
  name: network-latency-agent
  target_hosts:
    - cluster: "lorca-cluster-2"
      host_ip: ["147.102.13.108"]
    - cluster: "lorca-cluster-2"
      host_ip: ["147.102.13.108"]
    - cluster: "lorca-cluster-2"
      host_ip: ["147.102.13.108"]
  parameters:
    interval: 15

otel-collector:
  otelCollector:
    clusterName: "lorca-cluster-2"
