apiVersion: v2
name: observability_operator
description: Observability Operator for iot-edge-north-07
type: application
version: 0.1.0
dependencies:
  - name: otel-collector
    version: 0.1.0
    repository: "file://../otel_collector"
  - name: kepler
    version: "0.6.1"
    repository: "https://sustainable-computing-io.github.io/kepler-helm-chart"
  - name: prometheus-node-exporter
    version: "4.55.0"
    repository: "https://prometheus-community.github.io/helm-charts"
  - name: kube-state-metrics
    version: "7.4.0"
    repository: "https://prometheus-community.github.io/helm-charts"
  - name: network-latency
    version: "0.1.0"
    repository: "https://gitlab.com/api/v4/projects/44429468/packages/helm/stable"
  - name: fluent-bit
    version: "0.57.6"
    repository: "https://fluent.github.io/helm-charts"
