# Uncomment and fill in only the blocks for included dependencies.

# prometheus-node-exporter:
node-exporter:
  fullnameOverride: node-exporter

# network-latency:
network-latency:
  name: network-latency-agent
  target_hosts:
    - cluster: "iot-edge-north-07"
      host_ip:
        - "10.0.1.5"
        - "10.0.1.6"
        - "10.0.1.7"
  parameters:
    interval: 10

otelCollector:
  clusterName: "iot-edge-north-07"
