otelCollector:
  clusterName: "edge-events-only-03"
  scrapeInterval: 30s
  evaluationInterval: 5s
  deploymentName: otel-collector
  configMapName: otel-collector-config
  configChecksum: "aebbb87d32608a6cbf4d60bf9f0a7a575b2f2ac5993a772741f9ffb51b2b427f"
  serviceName: otel-collector
  replicas: 1
  image:
    registry: otel
    name: opentelemetry-collector-contrib
    tag: "0.98.0"
  exporters:
    otlp:
      host: "events-collector.monitoring.svc"
      port: 4318
      tls:
        insecure: true
