otelCollector:
  clusterName: "edge-events-only-03"
  scrapeInterval: 30s
  evaluationInterval: 5s
  deploymentName: otel-collector
  configMapName: otel-collector-config
  configChecksum: "70e55ff68e0cbdf83075003ab95ad2b727de7f0e5a13c0c4685d981770606639"
  serviceName: otel-collector
  replicas: 1
  image:
    registry: otel
    name: opentelemetry-collector-contrib
    tag: "0.98.0"
  exporters:
    otlp:
      host: "events-collector.monitoring.svc"
      port: 4318
      tls:
        insecure: true
