apiVersion: v2
name: observability_operator
setDescription: Observability Operator for cloud-prod-eu-1
type: application
version: 0.1.0
dependencies:
  - name: otel-collector
    version: 0.1.0
    repository: "file://../otel_collector"
  - name: prometheus-node-exporter
    version: 4.55.0
    repository: "https://prometheus-community.github.io/helm-charts"
