otelCollector:
  clusterName: athens_k3s_cluster
  deploymentName: otel-collector
  replicas: 1
  configMapName: otel-collector-config-map
  serviceName: otel-collector-service
  image:
    registry: otel
    name: opentelemetry-collector
    tag: latest
  scrapeInterval: 15s
  evaluationInterval: 15s
  exporters:
    otlp:
      host: 192.168.2.105
      port: 4318
    tls:
      insecure: true
