otelCollector:
  clusterName: nuc_ntua_cluster
  deploymentName: otel-collector
  replicas: 1
  configMapName: otel-collector-config-map
  serviceName: otel-collector-service
  image:
    registry: otel
    name: opentelemetry-collector
    tag: latest
  scrapeInterval: 8s
  evaluationInterval: 8s
  exporters:
    otlp:
      host: 147.102.13.110
      port: 4318
  tls:
    insecure: true