apiVersion: v2
name: observability_operator
setDescription: Observability Operator for trace-only-staging-01
type: application
version: 0.1.0
dependencies:
  - name: otel-collector
    version: 0.1.0
    repository: "file://../otel_collector"
