kepler:
  fullnameOverride: kepler
prometheus-node-exporter:
  fullnameOverride: node-exporter
otelCollector:
  clusterName: athens_k8s_cluster
  exporters:
    otlp:
      host: 147.102.13.108
      port: 4318
      tls:
        insecure: true
  scrapeInterval: 8s
  evaluationInterval: 5s
  pipelines:
    metrics:
      receivers:
        - prometheus
      processors:
        - resource
        - batch
      exporters:
        - otlp
  ports:
    otlp-grpc:
      port: 4317
      targetPort: 4317
    otlp-http:
      port: 4318
      targetPort: 4318
  configMapName: otel-collector-config
  deploymentName: otel-collector
  serviceName: otel-collector
  replicas: 1
  image:
    registry: otelcol
    name: otel-collector
    tag: 0.92.0