otelCollector:
  clusterName: "metrics-only-cluster-02"
  scrapeInterval: 15s
  evaluationInterval: 5s
  deploymentName: otel-collector
  configMapName: otel-collector-config
  configChecksum: "fd10ba90d7058fb8a5713c7aab052384f0e86f132152615bafd19c208f87b76c"
  serviceName: otel-collector
  replicas: 1
  image:
    registry: otel
    name: opentelemetry-collector-contrib
    tag: "0.98.0"
  exporters:
    otlp:
      host: "metrics-collector.infra.svc"
      port: 4318
      tls:
        insecure: true
