otelCollector:
  clusterName: "infra-ci-build-01"
  scrapeInterval: 60s
  evaluationInterval: 60s
  deploymentName: otel-collector
  configMapName: otel-collector-config
  configChecksum: "f9c92aa8c4c90605514e281bee09b17e9abaf2dfde649b9be6329e159b9342f5"
  serviceName: otel-collector
  replicas: 1
  image:
    registry: otel
    name: opentelemetry-collector-contrib
    tag: "0.98.0"
  exporters:
    otlp:
      host: "audit-collector.ci-infra.svc"
      port: 4318
      tls:
        insecure: true
