otelCollector:
  clusterName: "infra-ci-build-01"
  scrapeInterval: 60s
  evaluationInterval: 60s
  deploymentName: otel-collector
  configMapName: otel-collector-config
  configChecksum: "dc2484aec90c5f2442f57c873dd64778252b517b350d59ef8aa53ee4c66b6acd"
  serviceName: otel-collector
  replicas: 1
  image:
    registry: otel
    name: opentelemetry-collector-contrib
    tag: "0.98.0"
  exporters:
    otlp:
      host: "audit-collector.ci-infra.svc"
      port: 4318
      tls:
        insecure: true
  includeOtlpPipeline: true
  includeK8sEventsPipeline: true