apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ .Values.otelCollector.serviceAccountName }}-clusterrolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ .Values.otelCollector.serviceAccountName }}-clusterrole
subjects:
  - kind: ServiceAccount
    name: {{ .Values.otelCollector.serviceAccountName }}
    namespace: {{ .Release.Namespace }}
