apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.otelCollector.deploymentName }}
spec:
  replicas: {{ .Values.otelCollector.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.otelCollector.deploymentName }}
  template:
    metadata:
      labels:
        app: {{ .Values.otelCollector.deploymentName }}
    spec:
      serviceAccountName: otel-collector-serviceaccount
      containers:
        - name: otel-collector
          image: "{{ .Values.otelCollector.image.registry }}/{{ .Values.otelCollector.image.name }}:{{ .Values.otelCollector.image.tag }}"
          args: ["--config=/conf/config.yaml"]
          ports:
            - containerPort: 4317
            - containerPort: 4318
            - containerPort: 13133
          volumeMounts:
            - name: config
              mountPath: /conf
      volumes:
        - name: config
          configMap:
            name: {{ .Values.otelCollector.configMapName }}