apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.otelCollector.configMapName }}
  labels:
    app: {{ .Values.otelCollector.deploymentName }}
data:
  config.yaml: |
    extensions:
      health_check:
        endpoint: 0.0.0.0:13133
    receivers:
      prometheus:
        config:
          global:
            scrape_interval: {{ .Values.otelCollector.scrapeInterval }}
            evaluation_interval: {{ .Values.otelCollector.evaluationInterval }}
          scrape_configs:
{{- range .Values.otelCollector.scrapeJobs }}
            - job_name: "{{ .job_name }}"
              kubernetes_sd_configs:
{{ toYaml .kubernetes_sd_configs | indent 16 }}
              relabel_configs:
{{ toYaml .relabel_configs | indent 16 }}
{{- end }}
    processors:
      batch: {}
      resource:
        attributes:
          - key: cluster
            value: "{{ .Values.otelCollector.clusterName }}"
            action: insert
    exporters:
      otlp:
        endpoint: "{{ .Values.otelCollector.exporters.otlp.host }}:{{ .Values.otelCollector.exporters.otlp.port }}"
        tls:
          insecure: {{ .Values.otelCollector.exporters.tls.insecure }}
    service:
      pipelines:
        metrics:
          receivers: [prometheus]
          processors: [batch,resource]
          exporters: [otlp]
