apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.otelCollector.configMapName }}
data:
  otel-collector-config.yaml: |
    receivers:
{{- toYaml .Values.receivers | nindent 6 }}
    processors:
{{- toYaml .Values.processors | nindent 6 }}
    exporters:
{{- toYaml .Values.exporters | nindent 6 }}
    service:
{{- toYaml .Values.service | nindent 6 }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.otelCollector.deploymentName }}
spec:
  replicas: {{ .Values.otelCollector.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.otelCollector.deploymentName }}
  template:
    metadata:
      labels:
        app: {{ .Values.otelCollector.deploymentName }}
    spec:
      serviceAccountName: otel-collector-serviceaccount
      containers:
        - name: otel-collector
          image: "{{ .Values.otelCollector.image.registry }}/{{ .Values.otelCollector.image.name }}:{{ .Values.otelCollector.image.tag }}"
          args: ["--config=/conf/otel-collector-config.yaml"]
          ports:
            - containerPort: 4317
              name: otel-grpc
            - containerPort: 4318
              name: otel-http
          volumeMounts:
            - name: config
              mountPath: /conf
      volumes:
        - name: config
          configMap:
            name: {{ .Values.otelCollector.configMapName }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.otelCollector.serviceName }}
spec:
  selector:
    app: {{ .Values.otelCollector.deploymentName }}
  ports:
    - name: otlp-grpc
      port: 4317
      targetPort: 4317
    - name: otlp-http
      port: 4318
      targetPort: 4318
