apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.otelCollector.serviceName }}
  labels:
    app: {{ .Values.otelCollector.deploymentName }}
spec:
  selector:
    app: {{ .Values.otelCollector.deploymentName }}
  ports:
    - name: otlp-http
      port: 4318
      targetPort: 4318