otelCollector:
  clusterName: "edge-gw-probe-01"
  scrapeInterval: 15s
  evaluationInterval: 15s
  deploymentName: otel-collector
  configMapName: otel-collector-config
  configChecksum: "0230fafd3dedd591a00f44927189dd1cb93d1e8da69bf042bfbf932b3e8e30eb"
  serviceName: otel-collector
  replicas: 1
  image:
    registry: otel
    name: opentelemetry-collector-contrib
    tag: "0.98.0"
  exporters:
    otlp:
      host: "probe-collector.edge.svc"
      port: 4318
      tls:
        insecure: true
