otelCollector:
  clusterName: "edge-gw-probe-01"
  scrapeInterval: 15s
  evaluationInterval: 5s
  deploymentName: otel-collector
  configMapName: otel-collector-config
  configChecksum: "868889dbb3e200c71c725ce102ee7889bdae4b59917e3974bfb46ac33cd200ca"
  serviceName: otel-collector
  replicas: 1
  image:
    registry: otel
    name: opentelemetry-collector-contrib
    tag: "0.98.0"
  exporters:
    otlp:
      host: "probe-collector.edge.svc"
      port: 4318
      tls:
        insecure: true
