otelCollector:
  clusterName: "edge-gw-probe-01"
  scrapeInterval: 15s
  evaluationInterval: 5s
  deploymentName: otel-collector
  configMapName: otel-collector-config
  configChecksum: "e53beabf819937a8e2f3db2064b2877dfe582ec2eba3558fd06a9a1a98641bfd"
  serviceName: otel-collector
  replicas: 1
  image:
    registry: otel
    name: opentelemetry-collector-contrib
    tag: "0.98.0"
  exporters:
    otlp:
      host: "probe-collector.edge.svc"
      port: 4318
      tls:
        insecure: true