otelCollector:
  clusterName: "green-compute-eu-02"
  scrapeInterval: 20s
  evaluationInterval: 5s
  deploymentName: otel-collector
  configMapName: otel-collector-config
  configChecksum: "48d02c5db5564737ed3503abf9716fa74237d1359d000179201cb8816f75e418"
  serviceName: otel-collector
  replicas: 1
  image:
    registry: otel
    name: opentelemetry-collector-contrib
    tag: "0.98.0"
  exporters:
    otlp:
      host: "energy-collector.infra.local"
      port: 4318
      tls:
        insecure: true
