otelCollector:
  clusterName: "green-compute-eu-02"
  scrapeInterval: 20s
  evaluationInterval: 20s
  deploymentName: otel-collector
  configMapName: otel-collector-config
  configChecksum: "f5d99d2dc2933ba243ab9017077e991c1edb1687f28c1bba1def7304d1b6ffae"
  serviceName: otel-collector
  replicas: 1
  image:
    registry: otel
    name: opentelemetry-collector-contrib
    tag: "0.98.0"
  exporters:
    otlp:
      host: "energy-collector.infra.local"
      port: 4318
      tls:
        insecure: true