otelCollector:
  clusterName: "green-compute-eu-02"
  scrapeInterval: 20s
  evaluationInterval: 20s
  deploymentName: otel-collector
  configMapName: otel-collector-config
  configChecksum: "d2d797c6fd4acaad35eb588081073679664765df445300adbb180aafb18d393a"
  serviceName: otel-collector
  replicas: 1
  image:
    registry: otel
    name: opentelemetry-collector-contrib
    tag: "0.98.0"
  exporters:
    otlp:
      host: "energy-collector.infra.local"
      port: 4318
      tls:
        insecure: true
