otelCollector:
  clusterName: "green-compute-eu-02"
  scrapeInterval: 20s
  evaluationInterval: 5s
  deploymentName: otel-collector
  configMapName: otel-collector-config
  configChecksum: "c108dd63200f9ed90d0aadd1ccd5a5f29350288c64b291839e7d9f9b10290199"
  serviceName: otel-collector
  replicas: 1
  image:
    registry: otel
    name: opentelemetry-collector-contrib
    tag: "0.98.0"
  exporters:
    otlp:
      host: "energy-collector.infra.local"
      port: 4318
      tls:
        insecure: true
