otelCollector:
  clusterName: "metrics-only-cluster-02"
  scrapeInterval: 15s
  evaluationInterval: 5s
  deploymentName: otel-collector
  configMapName: otel-collector-config
  configChecksum: "28bcbc6a337b1ce02d7c59cbe8c92ef59c1832ecdba57d3576cc635d8c6730ad"
  serviceName: otel-collector
  replicas: 1
  image:
    registry: otel
    name: opentelemetry-collector-contrib
    tag: "0.98.0"
  exporters:
    otlp:
      host: "metrics-collector.infra.svc"
      port: 4318
      tls:
        insecure: true
