otelCollector:
  clusterName: "metrics-only-cluster-02"
  scrapeInterval: 15s
  evaluationInterval: 5s
  deploymentName: otel-collector
  configMapName: otel-collector-config
  configChecksum: "95fb310e0b10f353ee73d88aec392a7b5053ab43d3d02cdd28c9934187729a35"
  serviceName: otel-collector
  replicas: 1
  image:
    registry: otel
    name: opentelemetry-collector-contrib
    tag: "0.98.0"
  exporters:
    otlp:
      host: "metrics-collector.infra.svc"
      port: 4318
      tls:
        insecure: true
