otelCollector:
  clusterName: "metrics-only-cluster-02"
  scrapeInterval: 15s
  evaluationInterval: 15s
  deploymentName: otel-collector
  configMapName: otel-collector-config
  configChecksum: "e659b73863cc0ae2c80dcd04c355be0fdca067b3e143c3402ad7d3c408dcda7b"
  serviceName: otel-collector
  replicas: 1
  image:
    registry: otel
    name: opentelemetry-collector-contrib
    tag: "0.98.0"
  exporters:
    otlp:
      host: "metrics-collector.infra.svc"
      port: 4318
      tls:
        insecure: true
