otelCollector:
  clusterName: "multi-probe-datacenter-01"
  scrapeInterval: 10s
  evaluationInterval: 5s
  deploymentName: otel-collector
  configMapName: otel-collector-config
  configChecksum: "cbe69bd2c097c086227d57f0b19c4ed8ab56da05e21c76465c8e444e6b07913e"
  serviceName: otel-collector
  replicas: 1
  image:
    registry: otel
    name: opentelemetry-collector-contrib
    tag: "0.98.0"
  exporters:
    otlp:
      host: "otel-collector.dc01.svc"
      port: 4318
      tls:
        insecure: true
