otelCollector:
  clusterName: "multi-probe-datacenter-01"
  scrapeInterval: 10s
  evaluationInterval: 5s
  deploymentName: otel-collector
  configMapName: otel-collector-config
  configChecksum: "341402b7bb768526177f8480c2e5b5a8af49a2d69ca936ffd6fa6c3bfdeded4b"
  serviceName: otel-collector
  replicas: 1
  image:
    registry: otel
    name: opentelemetry-collector-contrib
    tag: "0.98.0"
  exporters:
    otlp:
      host: "otel-collector.dc01.svc"
      port: 4318
      tls:
        insecure: true
