# kepler:
#   fullnameOverride: kepler

# prometheus-node-exporter:
#   fullnameOverride: node-exporter

kepler:
  fullnameOverride: kepler

prometheus-node-exporter:
  fullnameOverride: node-exporter
