apiVersion: v2
name: observability-operator
description: Helm chart for deploying observability operator.
type: application
version: 0.1.0
appVersion: dev
dependencies:
  - name: otel-collector
    version: 0.1.0
    repository: "file://../otel_collector"
  - name: network-latency-agent
    version: 0.1.0
    repository: "https://gitlab.com/api/v4/projects/44429468/packages/helm/stable"