otelCollector:
  clusterName: "cloud-prod-eu-1"
  scrapeInterval: 30s
  evaluationInterval: 30s
  deploymentName: otel-collector
  configMapName: otel-collector-config
  configChecksum: "30be2a9482fc67017eafd7045a1465e6869da530af910aff92b4101cfa41e3d0"
  serviceName: otel-collector
  replicas: 1
  image:
    registry: otel
    name: opentelemetry-collector-contrib
    tag: "0.98.0"
  exporters:
    otlp:
      host: "otel-gateway.monitoring.svc.cluster.local"
      port: 4318
      tls:
        insecure: true