otelCollector:
  clusterName: "cloud-prod-eu-1"
  scrapeInterval: 30s
  evaluationInterval: 5s
  deploymentName: otel-collector
  configMapName: otel-collector-config
  configChecksum: "cb2ba784f7aab0ae1fdc966ba4c1c5758b21173382360cd0f3517c53f5bee10a"
  serviceName: otel-collector
  replicas: 1
  image:
    registry: otel
    name: opentelemetry-collector-contrib
    tag: "0.98.0"
  exporters:
    otlp:
      host: "otel-gateway.monitoring.svc.cluster.local"
      port: 4318
      tls:
        insecure: true
