otelCollector:
  clusterName: "deep-obs-cluster-07"
  scrapeInterval: 5s
  evaluationInterval: 5s
  deploymentName: otel-collector
  configMapName: otel-collector-config
  configChecksum: "ff717299770cf012c4aaa53dda6e4283bcae53f16af61a1f05109d0698ae304b"
  serviceName: otel-collector
  replicas: 1
  image:
    registry: otel
    name: opentelemetry-collector-contrib
    tag: "0.98.0"
  exporters:
    otlp:
      host: "full-collector.ops.svc"
      port: 4318
      tls:
        insecure: true
