otelCollector:
  clusterName: "deep-obs-cluster-07"
  scrapeInterval: 5s
  evaluationInterval: 5s
  deploymentName: otel-collector
  configMapName: otel-collector-config
  configChecksum: "0d16729bc307ca194a541eda2e11139c08c56a47fb860e1a190a39b3ec125c58"
  serviceName: otel-collector
  replicas: 1
  image:
    registry: otel
    name: opentelemetry-collector-contrib
    tag: "0.98.0"
  exporters:
    otlp:
      host: "full-collector.ops.svc"
      port: 4318
      tls:
        insecure: true