# Included dependencies overrides

# otelCollector parent values (required for NOTES and subchart inheritance)
otelCollector:
  clusterName: "cloud-prod-eu-1"

# prometheus-node-exporter:
prometheus-node-exporter:
  fullnameOverride: node-exporter

# other dependencies can remain commented out
# kepler:
#   fullnameOverride: kepler

# kube-state-metrics:
#   fullnameOverride: kube-state-metrics

# network-latency:
#   name: network-latency-agent
#   target_hosts:
#     - cluster: "cloud-prod-eu-1"
#       host_ip: []
#   parameters:
#     interval: 5

# fluent-bit:
#   fullnameOverride: fluent-bit
#   <see Fluent Bit section below for full config>
