otelCollector:
  clusterName: "datacenter-south-02"
  scrapeInterval: 10s
  evaluationInterval: 10s
  deploymentName: otel-collector
  configMapName: otel-collector-config
  configChecksum: "88a70a9e52f9da7423a70b4b47660684d93cb746890767993bb319fba378ec4c"
  serviceName: otel-collector
  replicas: 1
  image:
    registry: otel
    name: opentelemetry-collector-contrib
    tag: "0.98.0"
  exporters:
    otlp:
      host: "otel-collector.observability.svc"
      port: 4318
      tls:
        insecure: true
