otelCollector:
  clusterName: "datacenter-south-02"
  scrapeInterval: 10s
  evaluationInterval: 10s
  deploymentName: otel-collector
  configMapName: otel-collector-config
  configChecksum: "a1a97be0b103beb81598a07a7734baef59c74d81178457cc05f3d2a68fe76f08"
  serviceName: otel-collector
  replicas: 1
  image:
    registry: otel
    name: opentelemetry-collector-contrib
    tag: "0.98.0"
  exporters:
    otlp:
      host: "otel-collector.observability.svc"
      port: 4318
      tls:
        insecure: true