otelCollector:
  clusterName: "datacenter-south-02"
  scrapeInterval: 10s
  evaluationInterval: 10s
  deploymentName: otel-collector
  configMapName: otel-collector-config
  configChecksum: "bcbf19a8727d1b0bb0b82224aa85e7c58fe6b4731bbf7485f56a6558574acc65"
  serviceName: otel-collector
  replicas: 1
  image:
    registry: otel
    name: opentelemetry-collector-contrib
    tag: "0.98.0"
  exporters:
    otlp:
      host: "otel-collector.observability.svc"
      port: 4318
      tls:
        insecure: true
