otelCollector:
  clusterName: "metrics-only-cluster-02"

kepler:
  fullnameOverride: kepler

prometheus-node-exporter:
  fullnameOverride: node-exporter

kube-state-metrics:
  fullnameOverride: kube-state-metrics