otelCollector:
  clusterName: "alex_k8s_cluster"
  scrapeInterval: 20s
  evaluationInterval: 5s
  deploymentName: otel-collector
  configMapName: otel-collector-config
  configChecksum: "c4a6401f090208b9532dae5352d15d5e7986b495986e7b07117368a6a9ce7a7b"
  serviceName: otel-collector
  replicas: 1
  image:
    registry: otel
    name: opentelemetry-collector-contrib
    tag: "0.98.0"
  exporters:
    otlp:
      host: "147.102.7.110"
      port: 4318
      tls:
        insecure: true