otelCollector:
  clusterName: "alex_k8s_cluster"
  scrapeInterval: 30s
  evaluationInterval: 5s
  deploymentName: otel-collector
  configMapName: otel-collector-config
  configChecksum: "3abf716bf63def60d2d855a99349aa50105baf9356b91e2617f00d0e9f228b88"
  serviceName: otel-collector
  replicas: 1
  image:
    registry: otel
    name: opentelemetry-collector-contrib
    tag: "0.98.0"
  exporters:
    otlp:
      host: "147.102.7.110"
      port: 4318
      tls:
        insecure: true
