otelCollector:
  clusterName: "greg_k8s_cluster"
  scrapeInterval: 5s
  evaluationInterval: 5s
  deploymentName: otel-collector
  configMapName: otel-collector-config
  configChecksum: "309b68a19a3bfbcc94ad6a52c324be7647456e926d8033edcfec72a598e5899d"
  serviceName: otel-collector
  replicas: 1
  image:
    registry: otel
    name: opentelemetry-collector-contrib
    tag: "0.98.0"
  exporters:
    otlp:
      host: "147.102.7.110"
      port: 4318
      tls:
        insecure: true
