otelCollector:
  clusterName: "greg_k8s_cluster"
  scrapeInterval: 5s
  evaluationInterval: 5s
  deploymentName: otel-collector
  configMapName: otel-collector-config
  configChecksum: "8f4099953b1697d3ad571114fba6dbdc26ede9134954ee811849ade652591881"
  serviceName: otel-collector
  replicas: 1
  image:
    registry: otel
    name: opentelemetry-collector-contrib
    tag: "0.98.0"
  exporters:
    otlp:
      host: "147.102.7.110"
      port: 4318
      tls:
        insecure: true
