apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.otelCollector.configMapName }}
data:
  collector.yaml: |
    receivers:
      prometheus:
        config:
          global:
            scrape_interval: {{ .Values.otelCollector.scrapeInterval }}
            evaluation_interval: {{ .Values.otelCollector.evaluationInterval }}
          scrape_configs:
{{- range .Values.otelCollector.scrapeConfigs }}
            - {{ toYaml . | nindent 14 }}
{{- end }}
    processors:
      batch: {}
      resource:
        attributes:
          - key: cluster
            value: {{ .Values.otelCollector.clusterName }}
            action: insert
    exporters:
      otlp:
        endpoint: {{ .Values.otelCollector.exporters.otlp.host }}:{{ .Values.otelCollector.exporters.otlp.port }}
        tls:
          insecure: {{ .Values.otelCollector.exporters.tls.insecure }}
    service:
      pipelines:
        metrics:
          receivers: [prometheus]
          processors: [resource,batch]
          exporters: [otlp]