fluent-bit:
  config:
    filters: "[FILTER]\n    Name          modify\n    Match         k3s.*\n    Add\
      \           log_source k3s\n    Add           service_name k3s-cluster\n[FILTER]\n\
      \    Name          modify\n    Match         syslog.*\n    Add           log_source\
      \ syslog\n    Add           service_name os-systemd\n[FILTER]\n    Name    \
      \      modify\n    Match         node.system.*\n    Add           log_source\
      \ containerd\n    Add           service_name container-runtime\n"
    inputs: "[INPUT]\n    Name           tail\n    Tag            k3s.*\n    Path\
      \           /var/log/k3s.log\n[INPUT]\n    Name           tail\n    Tag    \
      \        syslog.*\n    Path           /var/log/syslog\n[INPUT]\n    Name   \
      \        systemd\n    Tag            node.system.*\n    Path           /run/systemd/journal\n\
      \    Systemd_Filter _SYSTEMD_UNIT=containerd\n"
    outputs: "[OUTPUT]\n    Name            opentelemetry\n    Match           *\n\
      \    Host            otel-collector\n    Port            4318\n    Logs_URI\
      \        /v1/logs\n    Tls             Off\n    Logs_body_key   log\n    Logs_body_key_attributes\
      \ true\n    Logs_attributes_metadata_key attributes\n    Logs_resource_metadata_key\
      \ resource\n    Logs_instrumentation_scope_metadata_key scope"
  extraVolumeMounts:
  - mountPath: /run/systemd/journal
    name: systemd-journal
    readOnly: true
  extraVolumes:
  - hostPath:
      path: /run/systemd/journal
    name: systemd-journal
  fullnameOverride: fluent-bit
kepler:
  fullnameOverride: kepler
kube-state-metrics:
  fullnameOverride: kube-state-metrics
network-latency:
  name: network-latency-agent
  parameters:
    interval: 10
  target_hosts:
  - cluster: greg_k8s_cluster
    host_ip:
    - 147.102.13.108
  - cluster: greg_k8s_cluster
    host_ip:
    - 147.102.13.108
  - cluster: greg_k8s_cluster
    host_ip:
    - 147.102.13.108
  - cluster: greg_k8s_cluster
    host_ip:
    - 147.102.13.109
prometheus-node-exporter:
  fullnameOverride: node-exporter
