otelCollector:
  clusterName: "k8s-audit-south-01"
  scrapeInterval: 30s
  evaluationInterval: 5s
  deploymentName: otel-collector
  configMapName: otel-collector-config
  configChecksum: "ae2f5798edd99987b584de00027bbda828a073638fab4436365c146c1da13ba1"
  serviceName: otel-collector
  replicas: 1
  image:
    registry: otel
    name: opentelemetry-collector-contrib
    tag: "0.98.0"
  exporters:
    otlp:
      host: "k8s-collector.platform.svc"
      port: 4318
      tls:
        insecure: true
