otelCollector:
  clusterName: "k8s-audit-south-01"
  scrapeInterval: 30s
  evaluationInterval: 5s
  deploymentName: otel-collector
  configMapName: otel-collector-config
  configChecksum: "30ce32fb102d1d0fb9df76b27980100ae4d2a39dfcc45c5447584efb94d49354"
  serviceName: otel-collector
  replicas: 1
  image:
    registry: otel
    name: opentelemetry-collector-contrib
    tag: "0.98.0"
  exporters:
    otlp:
      host: "k8s-collector.platform.svc"
      port: 4318
      tls:
        insecure: true
