otelCollector:
  clusterName: "k8s-audit-south-01"
  scrapeInterval: 30s
  evaluationInterval: 30s
  deploymentName: otel-collector
  configMapName: otel-collector-config
  configChecksum: "7cfea57b34f6a9cbbc70858825499207a849ac5ecf6027d7f997878fb3f850b7"
  serviceName: otel-collector
  replicas: 1
  image:
    registry: otel
    name: opentelemetry-collector-contrib
    tag: "0.98.0"
  exporters:
    otlp:
      host: "k8s-collector.platform.svc"
      port: 4318
      tls:
        insecure: true