otelCollector:
  clusterName: "dev-lab-02"
  scrapeInterval: 5s
  evaluationInterval: 5s
  deploymentName: otel-collector
  configMapName: otel-collector-config
  configChecksum: "ef25afe0f5584980780838b1434048091c0af9f531486e9ad5dde45cd6ee7549"
  serviceName: otel-collector
  replicas: 1
  image:
    registry: otel
    name: opentelemetry-collector-contrib
    tag: "0.98.0"
  exporters:
    otlp:
      host: "telemetry.dev.internal"
      port: 4318
      tls:
        insecure: true
