otelCollector:
  clusterName: "dev-lab-02"
  scrapeInterval: 5s
  evaluationInterval: 5s
  deploymentName: otel-collector
  configMapName: otel-collector-config
  configChecksum: "b1eb89aeec317302b9c14788ae99f548ca74fd62bf04a62216f0db128d71ca0f"
  serviceName: otel-collector
  replicas: 1
  image:
    registry: otel
    name: opentelemetry-collector-contrib
    tag: "0.98.0"
  exporters:
    otlp:
      host: "telemetry.dev.internal"
      port: 4318
      tls:
        insecure: true