---
# ConfigMap with Collector configuration
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.otelCollector.configMapName }}
  labels:
    app: {{ .Values.otelCollector.deploymentName }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  collector-config.yaml: |
    extensions:
      health_check:
        endpoint: 0.0.0.0:13133
    receivers:
      prometheus:
        config:
          global:
            scrape_interval: {{ .Values.otelCollector.scrapeInterval }}
            evaluation_interval: {{ .Values.otelCollector.evaluationInterval }}
          scrape_configs:
            - job_name: "cadvisor"
              scheme: "https"
              tls_config:
                ca_file: "/var/run/secrets/kubernetes.io/serviceaccount/ca.crt"
              bearer_token_file: "/var/run/secrets/kubernetes.io/serviceaccount/token"
              kubernetes_sd_configs:
                - role: "node"
              relabel_configs:
                - target_label: "__address__"
                  replacement: "kubernetes.default.svc:443"
                  action: "replace"
                - source_labels: [__meta_kubernetes_node_name]
                  regex: "(.+)"
                  target_label: "__metrics_path__"
                  replacement: "/api/v1/nodes/$${1}/proxy/metrics/cadvisor"
                  action: "replace"
            - job_name: "network-latency-agent"
              kubernetes_sd_configs:
                - role: "service"
              relabel_configs:
                - source_labels: [__meta_kubernetes_service_name]
                  action: keep
                  regex: network-latency-agent-service
    processors:
      resource:
        attributes:
          - key: cluster
            value: "{{ .Values.otelCollector.clusterName }}"
            action: insert
      batch: {}
    exporters:
      otlp:
        endpoint: "{{ .Values.otelCollector.exporters.otlp.host }}:{{ .Values.otelCollector.exporters.otlp.port }}"
        tls:
          insecure: {{ .Values.otelCollector.tls.insecure }}
    service:
      pipelines:
        metrics:
          receivers: [prometheus]
          processors: [resource,batch]
          exporters: [otlp]
---
# Deployment for the Collector
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.otelCollector.deploymentName }}
  labels:
    app: {{ .Values.otelCollector.deploymentName }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.otelCollector.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.otelCollector.deploymentName }}
  template:
    metadata:
      labels:
        app: {{ .Values.otelCollector.deploymentName }}
    spec:
      serviceAccountName: otel-collector-serviceaccount
      containers:
        - name: otel-collector
          image: "{{ .Values.otelCollector.image.registry }}/{{ .Values.otelCollector.image.name }}:{{ .Values.otelCollector.image.tag }}"
          args: ["--config=/conf/collector-config.yaml"]
          ports:
            - containerPort: 4318
          volumeMounts:
            - name: config
              mountPath: /conf
      volumes:
        - name: config
          configMap:
            name: {{ .Values.otelCollector.configMapName }}