otelCollector:
  clusterName: "alex_k8s_cluster"
  scrapeInterval: 15s
  evaluationInterval: 5s
  deploymentName: otel-collector
  configMapName: otel-collector-config
  configChecksum: "6069c1d0d428127199056e5e490d087777704231a9fa0600dbac3cb9407f2166"
  serviceName: otel-collector
  replicas: 1
  image:
    registry: otel
    name: opentelemetry-collector-contrib
    tag: "0.98.0"
  exporters:
    otlp:
      host: "147.102.7.110"
      port: 4318
      tls:
        insecure: true
