otelCollector:
  clusterName: "cloud-hybrid-west-02"
  scrapeInterval: 10s
  evaluationInterval: 10s
  deploymentName: otel-collector
  configMapName: otel-collector-config
  configChecksum: "8c725a1de9d24b4ade0f0fe5cc88f2902b4073929dcc575e80262ebf445958e8"
  serviceName: otel-collector
  replicas: 1
  image:
    registry: otel
    name: opentelemetry-collector-contrib
    tag: "0.98.0"
  exporters:
    otlp:
      host: "otel.platform.internal"
      port: 4318
      tls:
        insecure: true
