otelCollector:
  clusterName: "cloud-hybrid-west-02"
  scrapeInterval: 10s
  evaluationInterval: 10s
  deploymentName: otel-collector
  configMapName: otel-collector-config
  configChecksum: "6a9b3881c1b0b5435e42cf58639aba60723555280d9fe047cc85539e1fd1f96f"
  serviceName: otel-collector
  replicas: 1
  image:
    registry: otel
    name: opentelemetry-collector-contrib
    tag: "0.98.0"
  exporters:
    otlp:
      host: "otel.platform.internal"
      port: 4318
      tls:
        insecure: true