otelCollector:
  clusterName: "cloud-hybrid-west-02"
  scrapeInterval: 10s
  evaluationInterval: 5s
  deploymentName: otel-collector
  configMapName: otel-collector-config
  configChecksum: "3a0c41f9c90e066b788f2ee0a2d477381f91974df12504055b8cc2b95542936b"
  serviceName: otel-collector
  replicas: 1
  image:
    registry: otel
    name: opentelemetry-collector-contrib
    tag: "0.98.0"
  exporters:
    otlp:
      host: "otel.platform.internal"
      port: 4318
      tls:
        insecure: true
