otelCollector:
  clusterName: "trace-log-hybrid-01"
  scrapeInterval: 10s
  evaluationInterval: 10s
  deploymentName: otel-collector
  configMapName: otel-collector-config
  configChecksum: "1baf161516fae7a58fd530775e2dd16e8cd03268d93ec8ca382276c6eb187ed6"
  serviceName: otel-collector
  replicas: 1
  image:
    registry: otel
    name: opentelemetry-collector-contrib
    tag: "0.98.0"
  exporters:
    otlp:
      host: "hybrid-collector.ops.svc"
      port: 4318
      tls:
        insecure: true
