otelCollector:
  clusterName: "trace-log-hybrid-01"
  scrapeInterval: 10s
  evaluationInterval: 5s
  deploymentName: otel-collector
  configMapName: otel-collector-config
  configChecksum: "f661aea8097d89600c5c6c638798242a61da80d7959b316355aff69e1a56edd2"
  serviceName: otel-collector
  replicas: 1
  image:
    registry: otel
    name: opentelemetry-collector-contrib
    tag: "0.98.0"
  exporters:
    otlp:
      host: "hybrid-collector.ops.svc"
      port: 4318
      tls:
        insecure: true
