otelCollector:
  clusterName: "trace-log-hybrid-01"
  scrapeInterval: 10s
  evaluationInterval: 5s
  deploymentName: otel-collector
  configMapName: otel-collector-config
  configChecksum: "770c63f080dee73f85f548768d9e3c23c6d3dd2c54d9a6cc06c15ea4bf1dbc86"
  serviceName: otel-collector
  replicas: 1
  image:
    registry: otel
    name: opentelemetry-collector-contrib
    tag: "0.98.0"
  exporters:
    otlp:
      host: "hybrid-collector.ops.svc"
      port: 4318
      tls:
        insecure: true
